site_name: Billingo API v2 documentation (deprecated)

pages:
  - Usage: index.md
  - Authentication: auth.md
  - Invoices: invoices.md
  - Invoice Query: query.md
  - Clients: clients.md
  - Expenses: expenses.md
  - Products: products.md
  - Bank accounts: bank_accounts.md
  - Payment methods: payment_methods.md
  - VAT: vat.md
  - Currency: currency.md
  - Libraries: libraries.md
  - Changelog: changelog.md

theme: readthedocs
